name: Scheule test
on:
  schedule:
    - cron: "45 5 * * *"
  push:
jobs:
  jobA:
    name: schedule to run in 2 mins past every hr
    runs-on: ubuntu-latest
   
    steps:
      - name: checkout actions
        uses: actions/checkout@v7.0.1
      - name: print hostname
        run: |
          hostname
          mkdir new_folder1
          cd new_folder1
          touch file1.txt file2.txt file3.txt
          ls -l
