name: Scheule test
on:
  schedule:
    - cron: "2 * * * *"

jobs:
  jobA:
    name: schedule to run in 2 mins past every hr
    runs-on: ubuntu-latest
    steps:
      - name: print hostname
        run: hostname
